version: '3.0'

services:
  mongo-db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0.6
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - ${MONGO_DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']
